### ISSUE TITLE
failed to open database

### ISSUE THREAD

**Issue by buhman** [HalosGhost/pandabin#22]
Unlike a remote database, something that uses sqlite should JustWork™. Instead:

```
Aug 08 23:36:50 balin pandabin[20028]: Started
Aug 08 23:36:50 balin pandabin[20028]: Failed to open database: unable to open database file
Aug 08 23:36:50 balin pandabin[20028]: Ended
```

This error message could be more clear if the path to the database is also shown--this makes sense for this error because it is directly caused by the return value of `sqlite3_open`.

strace reveals the actual problem:

```
open("/home/halosghost/pandabin/db.sqlite", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

**Comment by HalosGhost** [comment]
Indeed, I managed to fail and put my own homedir in the code. That will be fixed tomorrow. Thank you for the report!
