### ISSUE TITLE
sqlite and concurrency

### ISSUE THREAD

**Issue by buhman** [HalosGhost/pandabin#26]
In SQLITE_OPEN_FULLMUTEX/SERIALIZED mode, all database/connection-level operations will block, which severely limits pandabin's concurrency, especially if either the acquire/release cycle and/or sqlite itself end up being slower than everything else.

**Comment by buhman** [comment]
Related: #25

**Comment by buhman** [comment]
I also think it would be somewhat fun to make pandabin support multiple embedded databases, like wiredtiger or leveldb.

**Comment by buhman** [comment]
Related: #27

**Comment by buhman** [comment]
I tested this, and in `NOMUTEX` mode, performance does increase slightly, but not significantly enough to make it worthwhile to bother with `SQLITE_BUSY` handling, IMO.

**Comment by HalosGhost** [comment]
I figured that might be the case since one of sqlite's priorities is being blindingly fast, and this is a net-bound application.

Thank you for the ground work though!
